add new message type for message epm->lv
Biobank-Sverige/clinical-trial-regulators-collaboration pull request #16
Opened 2024-12-18 14:37 UTC by thomaskrut

Förslag på lösning för ny meddelandetyp för svarsmeddelanden till LV, där endast ett fåtal fält är required, enligt #15 

Det finns nu en `simplifiedMessageType` som endast har `otherDocuments`, `messageReasonType`, `lvDiaryNumber` samt `to` och `from`. Jag har ändrat enumtyperna som tidigare hette `partyType` så att schemat differentierar på dessa, dvs om `to` är "LV" kommer meddelandet valideras som `simplifiedMessageType`, annars som `fullMessageType`.

2024-12-19 05:54 UTC, karatekaneen requested changes
Ser bra ut, en enum som har lite fel namn bara

2024-12-19 05:54 UTC, karatekaneen commented on src/schema/messageSchema.json
> +                                "$ref": "#/components/schemas/partyTypeEPM"
Denna typen av meddelanden kan komma från både EPM och RBC

2024-12-19 05:54 UTC, karatekaneen commented on src/schema/messageSchema.json
> +                        "$ref": "#/components/schemas/partyTypeEPM"
Även här kan to vara EPM eller RBC. Men om jag tänker rätt så kommer EPM eller RBC aldrig vara avsändaren här?

2024-12-19 07:19 UTC, thomaskrut commented on src/schema/messageSchema.json
> +                        "$ref": "#/components/schemas/partyTypeEPM"
Det stämmer, detta är den ursprungliga meddelandetypen, och ```from``` har då "LV" som enda möjliga värde.

2024-12-20 10:22 UTC, karatekaneen approved these changes

2025-01-07 08:35 UTC, karatekaneen commented
Tolkar det som om det är konsensus här, tackar!

2025-01-07 08:36 UTC, merged